definitions:
  middleware.Response:
    properties:
      code:
        description: 自定义状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 提示信息
        type: string
      time:
        type: string
    type: object
  model.Article:
    properties:
      content:
        description: 内容
        type: string
      created_at:
        description: 创建时间
        type: string
      id:
        description: 主键
        type: integer
      status:
        allOf:
        - $ref: '#/definitions/model.ArticleStatus'
        description: 状态
        enum:
        - 0
        - 1
        - 2
      status_name:
        description: 状态名称
        type: string
      title:
        description: 标题
        type: string
      updated_at:
        description: 更新时间
        type: string
      user_id:
        description: 外键关联用户ID
        type: integer
    type: object
  model.ArticleResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      status:
        type: integer
      status_name:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  model.ArticleStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      Draft: 草稿
      Pending: 待审核
      Published: 已发布
    x-enum-varnames:
    - Draft
    - Pending
    - Published
  model.User:
    properties:
      account:
        description: 账号，唯一
        type: string
      created_at:
        description: 创建时间
        type: string
      email:
        description: 邮箱，唯一
        type: string
      id:
        type: integer
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
      role:
        description: 角色
        type: string
      status:
        description: 状态 active/disabled
        type: string
      updated_at:
        description: 更新时间
        type: string
      username:
        description: 用户名，唯一
        type: string
      uuid:
        description: 用户唯一标识
        type: string
    required:
    - password
    - username
    type: object
  model.UserResponse:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      phone:
        type: string
      role:
        type: string
      status:
        type: string
      updated_at:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/article/{id}:
    put:
      description: 更新文章
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      responses:
        "200":
          description: 更新成功返回
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 更新文章
      tags:
      - 文章
  /api/article/{uuid}/status:
    put:
      description: 更新文章状态
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: '请求体 (status: 0=Draft, 1=Pending, 2=Published)'
        in: body
        name: request
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: 更新成功返回
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 更新文章状态
      tags:
      - 文章
  /api/article/add:
    post:
      description: 添加文章
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      responses:
        "200":
          description: 添加成功返回
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 添加文章
      tags:
      - 文章
  /api/article/get/:id:
    get:
      description: 查询文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: 文章信息
          schema:
            $ref: '#/definitions/model.ArticleResponse'
      summary: 查询文章
      tags:
      - 文章
  /api/articles/delete/:id:
    delete:
      description: 删除文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: 文章信息
          schema:
            type: string
      summary: 删除文章
      tags:
      - 文章
  /api/comment/add:
    post:
      consumes:
      - multipart/form-data
      description: 添加评论
      parameters:
      - description: 评论内容
        in: formData
        name: content
        required: true
        type: string
      - description: 所属帖子ID
        in: formData
        name: postId
        required: true
        type: integer
      - description: 评论用户ID
        in: formData
        name: userId
        required: true
        type: integer
      - description: 父评论ID
        in: formData
        name: parentId
        type: integer
      - description: 资源类型 image/video
        in: formData
        name: type
        required: true
        type: integer
      - description: 上传文件
        in: formData
        name: files
        required: true
        type: file
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"操作成功"}'
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 添加评论
      tags:
      - 评论
  /api/comment/list:
    get:
      description: 获取评论列表
      parameters:
      - description: 帖子ID
        in: query
        name: postId
        required: true
        type: integer
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"操作成功"}'
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 获取评论列表
      tags:
      - 评论
  /api/user/add:
    post:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
      summary: 添加用户
      tags:
      - 用户
  /api/user/get/:id:
    get:
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户
  /api/user/list:
    get:
      description: 返回所有用户信息
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表
          schema:
            items:
              $ref: '#/definitions/model.UserResponse'
            type: array
      summary: 获取用户列表
      tags:
      - 用户
  /api/user/login:
    get:
      description: 登录
      parameters:
      - description: 用户邮箱
        in: query
        name: Email
        required: true
        type: string
      - description: 账号
        in: query
        name: Account
        required: true
        type: string
      - description: 手机号
        in: query
        name: Phone
        required: true
        type: string
      - description: 用户密码
        in: query
        name: Password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 登录
      tags:
      - 登录
  /api/user/refresh:
    post:
      consumes:
      - application/json
      description: 刷新token
      parameters:
      - description: 刷新token
        in: formData
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 刷新token
      tags:
      - 登录
  /api/user/update/password:
    post:
      description: 更新用户密码
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 更新用户密码
      tags:
      - 用户
  /api/user/update/user:
    post:
      description: 更新用户数据
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/middleware.Response'
      summary: 更新用户数据
      tags:
      - 用户
  /ws:
    get:
      consumes:
      - application/json
      description: 通过WebSocket建立连接
      produces:
      - application/json
      responses:
        "200":
          description: 连接成功
          schema:
            type: string
        "500":
          description: 连接失败
          schema:
            type: string
      summary: WebSocket连接
      tags:
      - websocket
swagger: "2.0"
